# Generated by Django 3.1.5 on 2021-01-07 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default=True, max_length=50)),
                ('Description', models.TextField()),
                ('Image_link', models.URLField()),
                ('Price', models.FloatField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField(default=0)),
                ('Order_placed_on', models.DateField(auto_now_add=True)),
                ('Order_updated_on', models.DateField(auto_now=True)),
                ('Status', models.CharField(choices=[('new', 'new'), ('paid', 'paid')], max_length=5)),
                ('Mode_of_payment', models.CharField(choices=[('cash', 'cash')], max_length=25)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineshopapp1.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Price', models.FloatField()),
                ('order_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineshopapp1.ordermodel')),
                ('product_Id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='onlineshopapp1.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
